name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  setup:
    runs-on: ubuntu-latest
    needs: analyze

  unit-test:
    runs-on: ubuntu-latest
    needs: setup

  build:
    runs-on: ubuntu-latest
    needs: unit-test
